GET http://localhost:3000/api/encargados

###

GET http://localhost:3000/api/encargados/608e3b4b41d62721a8073131

###

POST http://localhost:3000/api/encargados
Content-Type: application/json

{
    "nombre": "Andrés",
    "apellido": "Díaz",
    "cedula": "12321871",
    "cargo": "Gerente",
    "pais": "Venezuela"
}

###

PATCH http://localhost:3000/api/encargados/608e3b4b41d62721a8073131
Content-Type: application/json

{
    "nombre": "Pepe",
    "apellido": "López"
}

###

DELETE http://localhost:3000/api/encargados/608e3b4b41d62721a8073131